// Builds <outpost>/scripts/data.js (exports marsData and moonData) from data/raw_*.json.
//   npm run build-datajs        (after `npm run snapshot` for live values)
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { normalizeRawFile, toEngineData } from '../server/normalize.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUTPOST = path.resolve(process.env.OUTPOST_DIR || path.join(ROOT, '..'));

const build = async (body) => {
  const raw = JSON.parse(await fs.readFile(path.join(ROOT, 'data', `raw_${body}.json`), 'utf8'));
  const { power, weather } = normalizeRawFile(raw);
  return toEngineData(body, { power, weather }, { origin: raw.origin });
};

const mars = await build('mars');
const moon = await build('moon');
const text = `// AUTO-GENERATED by nasa-data-layer (npm run build-datajs). Plain values, no network calls.
// Units: solar_flux_wm2 W/m², temps °C, day_length_h hours, background_dose_msv_h mSv/h.
export const marsData = ${JSON.stringify(mars, null, 2)};

export const moonData = ${JSON.stringify(moon, null, 2)};
`;
const out = path.join(OUTPOST, 'scripts', 'data.js');
await fs.mkdir(path.dirname(out), { recursive: true });
await fs.writeFile(out, text);
console.log(`wrote ${out}`);
